name: Package and Publish NuGet

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: cd Bank && dotnet restore
      - name: Run unit tests
        run: cd Bank && dotnet test --collect:"XPlat Code Coverage"
      #- name: Analyze with SonarCloud
      #  uses: sonarsource/sonarcloud-github-action@v1
      #  with:
      #    sonar-token: ${{ secrets.SONAR_TOKEN }}
      - name: Build the project
        run: cd Bank && dotnet build
      - name: Create NuGet package
        run: cd Bank && dotnet pack --configuration Release
      - name: Publish NuGet package to GitHub Packages
        run: cd Bank && dotnet nuget push **/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        #run: cd Bank && dotnet nuget add source --username ${{ github.OWNER }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
        #run: cd Bank && dotnet nuget push ./bin/Release/*.nupkg --source "GitHub" --api-key ${{ secrets.GITHUB_TOKEN }}
