name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up DocFx
        run: |
          curl -LO https://github.com/dotnet/docfx/releases/download/v2.59.3/docfx.zip
          unzip docfx.zip -d $HOME/docfx
          export PATH=$HOME/docfx:$PATH
      - name: Generate documentation
        run: |
          docfx metadata docfx.json
          docfx build
      - name: Publish documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: _site
          target_branch: gh-pages
